package js.html;

/**
	The **`CanvasCaptureMediaStreamTrack`** interface of the Media Capture and Streams API represents the video track contained in a MediaStream being generated from a canvas following a call to HTMLCanvasElement.captureStream().
	
	[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasCaptureMediaStreamTrack)
**/
typedef ICanvasCaptureMediaStreamTrack = {
	/**
		The **`canvas`** read-only property of the CanvasCaptureMediaStreamTrack interface returns the HTMLCanvasElement from which frames are being captured.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasCaptureMediaStreamTrack/canvas)
	**/
	final canvas : js.html.CanvasElement;
	/**
		The **`requestFrame()`** method of the CanvasCaptureMediaStreamTrack interface requests that a frame be captured from the canvas and sent to the stream.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/CanvasCaptureMediaStreamTrack/requestFrame)
	**/
	function requestFrame():Void;
	/**
		The **`addEventListener()`** method of the EventTarget interface sets up a function that will be called whenever the specified event is delivered to the target.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener)
	**/
	@:overload(function(type:String, listener:EventListenerOrEventListenerObject, ?options:ts.AnyOf2<Bool, js.html.AddEventListenerOptions>):Void { })
	function addEventListener<K:(String)>(type:K, listener:(ev:Dynamic) -> Dynamic, ?options:ts.AnyOf2<Bool, js.html.AddEventListenerOptions>):Void;
	/**
		The **`removeEventListener()`** method of the EventTarget interface removes an event listener previously registered with EventTarget.addEventListener() from the target.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/removeEventListener)
	**/
	@:overload(function(type:String, listener:EventListenerOrEventListenerObject, ?options:ts.AnyOf2<Bool, js.html.EventListenerOptions>):Void { })
	function removeEventListener<K:(String)>(type:K, listener:(ev:Dynamic) -> Dynamic, ?options:ts.AnyOf2<Bool, js.html.EventListenerOptions>):Void;
	/**
		The **`contentHint`** property of the MediaStreamTrack interface is a string that hints at the type of content the track contains.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/contentHint)
	**/
	var contentHint : String;
	/**
		The **`enabled`** property of the `true` if the track is allowed to render the source stream or `false` if it is not.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/enabled)
	**/
	var enabled : Bool;
	/**
		The **`id`** read-only property of the MediaStreamTrack interface returns a string containing a unique identifier (GUID) for the track, which is generated by the user agent.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/id)
	**/
	final id : String;
	/**
		The **`kind`** read-only property of the MediaStreamTrack interface returns a string set to `'audio'` if the track is an audio track and to `'video'` if it is a video track.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/kind)
	**/
	final kind : String;
	/**
		The **`label`** read-only property of the MediaStreamTrack interface returns a string containing a user agent-assigned label that identifies the track source, as in `'internal microphone'`.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/label)
	**/
	final label : String;
	/**
		The **`muted`** read-only property of the indicating whether or not the track is currently unable to provide media output.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/muted)
	**/
	final muted : Bool;
	/**
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/ended_event)
	**/
	@:optional
	dynamic function onended(ev:js.html.Event):Dynamic;
	/**
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/mute_event)
	**/
	@:optional
	dynamic function onmute(ev:js.html.Event):Dynamic;
	/**
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/unmute_event)
	**/
	@:optional
	dynamic function onunmute(ev:js.html.Event):Dynamic;
	/**
		The **`readyState`** read-only property of the MediaStreamTrack interface returns an enumerated value giving the status of the track.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/readyState)
	**/
	final readyState : js.html.MediaStreamTrackState;
	/**
		The **`applyConstraints()`** method of the MediaStreamTrack interface applies a set of constraints to the track; these constraints let the website or app establish ideal values and acceptable ranges of values for the constrainable properties of the track, such as frame rate, dimensions, echo cancellation, and so forth.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/applyConstraints)
	**/
	function applyConstraints(?constraints:js.html.MediaTrackConstraints):js.lib.Promise<ts.Undefined>;
	/**
		The **`clone()`** method of the MediaStreamTrack interface creates a duplicate of the `MediaStreamTrack`.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/clone)
	**/
	function clone():js.html.MediaStreamTrack;
	/**
		The **`getCapabilities()`** method of the MediaStreamTrack interface returns an object detailing the accepted values or value range for each constrainable property of the associated `MediaStreamTrack`, based upon the platform and user agent.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/getCapabilities)
	**/
	function getCapabilities():MediaTrackCapabilities;
	/**
		The **`getConstraints()`** method of the MediaStreamTrack interface returns a recently established for the track using a prior call to constraints indicate values and ranges of values that the website or application has specified are required or acceptable for the included constrainable properties.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/getConstraints)
	**/
	function getConstraints():js.html.MediaTrackConstraints;
	/**
		The **`getSettings()`** method of the object containing the current values of each of the constrainable properties for the current `MediaStreamTrack`.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/getSettings)
	**/
	function getSettings():js.html.MediaTrackSettings;
	/**
		The **`stop()`** method of the MediaStreamTrack interface stops the track.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/MediaStreamTrack/stop)
	**/
	function stop():Void;
	/**
		The **`dispatchEvent()`** method of the EventTarget sends an Event to the object, (synchronously) invoking the affected event listeners in the appropriate order.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/EventTarget/dispatchEvent)
	**/
	function dispatchEvent(event:js.html.Event):Bool;
};