package js.html;

/**
	The **`PageRevealEvent`** event object is made available inside handler functions for the Window.pagereveal_event event.
	
	[MDN Reference](https://developer.mozilla.org/docs/Web/API/PageRevealEvent)
**/
@:native("PageRevealEvent") extern class PageRevealEvent {
	function new(type:String, ?eventInitDict:PageRevealEventInit);
	/**
		The **`viewTransition`** read-only property of the PageRevealEvent interface contains a ViewTransition object representing the active view transition for the cross-document navigation.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/PageRevealEvent/viewTransition)
	**/
	final viewTransition : Null<ViewTransition>;
	/**
		The **`bubbles`** read-only property of the Event interface indicates whether the event bubbles up through the DOM tree or not.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/bubbles)
	**/
	final bubbles : Bool;
	/**
		The **`cancelBubble`** property of the Event interface is deprecated.
	**/
	var cancelBubble : Bool;
	/**
		The **`cancelable`** read-only property of the Event interface indicates whether the event can be canceled, and therefore prevented as if the event never happened.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/cancelable)
	**/
	final cancelable : Bool;
	/**
		The read-only **`composed`** property of the or not the event will propagate across the shadow DOM boundary into the standard DOM.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composed)
	**/
	final composed : Bool;
	/**
		The **`currentTarget`** read-only property of the Event interface identifies the element to which the event handler has been attached.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/currentTarget)
	**/
	final currentTarget : Null<js.html.EventTarget>;
	/**
		The **`defaultPrevented`** read-only property of the Event interface returns a boolean value indicating whether or not the call to Event.preventDefault() canceled the event.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/defaultPrevented)
	**/
	final defaultPrevented : Bool;
	/**
		The **`eventPhase`** read-only property of the being evaluated.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/eventPhase)
	**/
	final eventPhase : Float;
	/**
		The **`isTrusted`** read-only property of the when the event was generated by the user agent (including via user actions and programmatic methods such as HTMLElement.focus()), and `false` when the event was dispatched via The only exception is the `click` event, which initializes the `isTrusted` property to `false` in user agents.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/isTrusted)
	**/
	final isTrusted : Bool;
	/**
		The Event property **`returnValue`** indicates whether the default action for this event has been prevented or not.
	**/
	var returnValue : Bool;
	/**
		The deprecated **`Event.srcElement`** is an alias for the Event.target property.
	**/
	final srcElement : Null<js.html.EventTarget>;
	/**
		The read-only **`target`** property of the dispatched.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/target)
	**/
	final target : Null<js.html.EventTarget>;
	/**
		The **`timeStamp`** read-only property of the Event interface returns the time (in milliseconds) at which the event was created.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/timeStamp)
	**/
	final timeStamp : Float;
	/**
		The **`type`** read-only property of the Event interface returns a string containing the event's type.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/type)
	**/
	final type : String;
	/**
		The **`composedPath()`** method of the Event interface returns the event's path which is an array of the objects on which listeners will be invoked.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composedPath)
	**/
	function composedPath():Array<js.html.EventTarget>;
	/**
		The **`Event.initEvent()`** method is used to initialize the value of an event created using Document.createEvent().
	**/
	function initEvent(type:String, ?bubbles:Bool, ?cancelable:Bool):Void;
	/**
		The **`preventDefault()`** method of the Event interface tells the user agent that if the event does not get explicitly handled, its default action should not be taken as it normally would be.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/preventDefault)
	**/
	function preventDefault():Void;
	/**
		The **`stopImmediatePropagation()`** method of the If several listeners are attached to the same element for the same event type, they are called in the order in which they were added.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/stopImmediatePropagation)
	**/
	function stopImmediatePropagation():Void;
	/**
		The **`stopPropagation()`** method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/stopPropagation)
	**/
	function stopPropagation():Void;
	final NONE : Int;
	final CAPTURING_PHASE : Int;
	final AT_TARGET : Int;
	final BUBBLING_PHASE : Int;
	static var prototype : PageRevealEvent;
}