package three;
@:jsRequire("three", "Audio") extern class Audio extends Object3D {
	function new(listener:AudioListener);
	var context : ts.html.IAudioContext;
	var gain : ts.html.IGainNode;
	var autoplay : Bool;
	var buffer : Null<Audio>;
	var detune : Float;
	var loop : Bool;
	var startTime : Float;
	var offset : Float;
	var playbackRate : Float;
	var isPlaying : Bool;
	var hasPlaybackControl : Bool;
	var sourceType : String;
	var source : ts.html.IAudioBufferSourceNode;
	var filters : std.Array<Dynamic>;
	function getOutput():ts.html.IGainNode;
	function setNodeSource(audioNode:ts.html.IAudioBufferSourceNode):Audio;
	function setMediaElementSource(mediaElement:ts.html.IMediaElementAudioSourceNode):Audio;
	function setBuffer(audioBuffer:AudioBuffer):Audio;
	function play():Audio;
	function onEnded():Void;
	function pause():Audio;
	function stop():Audio;
	function connect():Audio;
	function disconnect():Audio;
	function setDetune(value:Float):Audio;
	function getDetune():Float;
	function getFilters():std.Array<Dynamic>;
	@:overload(function(filter:Dynamic):Audio { })
	function setFilter(value:std.Array<Dynamic>):Audio;
	function getFilter():Dynamic;
	function setPlaybackRate(value:Float):Audio;
	function getPlaybackRate():Float;
	function getLoop():Bool;
	function setLoop(value:Bool):Void;
	function getVolume():Float;
	function setVolume(value:Float):Audio;
	function load(file:String):Audio;
}