function main() {
    Test.run('_generated-unit',"./unit/",[
        'ambient',
        'built-in',
        'class',
        'edge-cases',
        'enum',
        'export-array',
        'export-const',
        'export-default',
        'export-function',
        'export-object',
        'export=',
        'functions',
        'generics',
        'interface',
        'mapped-types',
        'modules',
        'named-tuple',
        'symbols',
        'tripple-slash-references',
        'ts4.1',
        'tuples',
        'type-parameters',
        'types',
        'unions-intersections',
    ],['--verbose', '--noLibWrap']);
}
