// Generated by Haxe 4.0.5
(function ($global) { "use strict";
var Express = require("express");
var Server = function() { };
Server.main = function() {
	var app = Express();
	var port = 3000;
	app.get("/",function(req,res,next) {
		return res.send("Hello World!");
	});
	app.listen(port,function() {
		console.log("Server.hx:11:","Example app listening at http://localhost:" + port);
		return;
	});
};
Server.main();
})({});
