// Generated by Haxe 4.0.5
(function ($global) { "use strict";
var Express = require("express");
var Main = function() { };
Main.main = function() {
	var app = Express();
	var port = 3000;
	app.get("/",function(req,res) {
		return res.send("Hello World!");
	});
	app.listen(port,function() {
		console.log("Main.hx:11:","Example app listening at http://localhost:" + port);
		return;
	});
};
Main.main();
})({});
