package js.html;
@:native("DOMMatrix") @tsInterface extern class DOMMatrix {
	function new(?init:haxe.extern.EitherType<String, std.Array<Float>>);
	var a : Float;
	var b : Float;
	var c : Float;
	var d : Float;
	var e : Float;
	var f : Float;
	var m11 : Float;
	var m12 : Float;
	var m13 : Float;
	var m14 : Float;
	var m21 : Float;
	var m22 : Float;
	var m23 : Float;
	var m24 : Float;
	var m31 : Float;
	var m32 : Float;
	var m33 : Float;
	var m34 : Float;
	var m41 : Float;
	var m42 : Float;
	var m43 : Float;
	var m44 : Float;
	function invertSelf():DOMMatrix;
	function multiplySelf(?other:DOMMatrixInit):DOMMatrix;
	function preMultiplySelf(?other:DOMMatrixInit):DOMMatrix;
	function rotateAxisAngleSelf(?x:Float, ?y:Float, ?z:Float, ?angle:Float):DOMMatrix;
	function rotateFromVectorSelf(?x:Float, ?y:Float):DOMMatrix;
	function rotateSelf(?rotX:Float, ?rotY:Float, ?rotZ:Float):DOMMatrix;
	function scale3dSelf(?scale:Float, ?originX:Float, ?originY:Float, ?originZ:Float):DOMMatrix;
	function scaleSelf(?scaleX:Float, ?scaleY:Float, ?scaleZ:Float, ?originX:Float, ?originY:Float, ?originZ:Float):DOMMatrix;
	function setMatrixValue(transformList:String):DOMMatrix;
	function skewXSelf(?sx:Float):DOMMatrix;
	function skewYSelf(?sy:Float):DOMMatrix;
	function translateSelf(?tx:Float, ?ty:Float, ?tz:Float):DOMMatrix;
	final is2D : Bool;
	final isIdentity : Bool;
	function flipX():DOMMatrix;
	function flipY():DOMMatrix;
	function inverse():DOMMatrix;
	function multiply(?other:DOMMatrixInit):DOMMatrix;
	function rotate(?rotX:Float, ?rotY:Float, ?rotZ:Float):DOMMatrix;
	function rotateAxisAngle(?x:Float, ?y:Float, ?z:Float, ?angle:Float):DOMMatrix;
	function rotateFromVector(?x:Float, ?y:Float):DOMMatrix;
	function scale(?scaleX:Float, ?scaleY:Float, ?scaleZ:Float, ?originX:Float, ?originY:Float, ?originZ:Float):DOMMatrix;
	function scale3d(?scale:Float, ?originX:Float, ?originY:Float, ?originZ:Float):DOMMatrix;
	function scaleNonUniform(?scaleX:Float, ?scaleY:Float):DOMMatrix;
	function skewX(?sx:Float):DOMMatrix;
	function skewY(?sy:Float):DOMMatrix;
	function toFloat32Array():js.lib.Float32Array;
	function toFloat64Array():js.lib.Float64Array;
	function toJSON():Any;
	function transformPoint(?point:DOMPointInit):DOMPoint;
	function translate(?tx:Float, ?ty:Float, ?tz:Float):DOMMatrix;
	static var prototype : DOMMatrix;
	static function fromFloat32Array(array32:js.lib.Float32Array):DOMMatrix;
	static function fromFloat64Array(array64:js.lib.Float64Array):DOMMatrix;
	static function fromMatrix(?other:DOMMatrixInit):DOMMatrix;
}