package js.html;
/**
	The results generated by evaluating an XPath expression within the context of a given node.
**/
@:native("XPathResult") @tsInterface extern class XPathResult {
	function new();
	final booleanValue : Bool;
	final invalidIteratorState : Bool;
	final numberValue : Float;
	final resultType : Float;
	final singleNodeValue : Null<Node>;
	final snapshotLength : Float;
	final stringValue : String;
	function iterateNext():Null<Node>;
	function snapshotItem(index:Float):Null<Node>;
	final ANY_TYPE : Float;
	final ANY_UNORDERED_NODE_TYPE : Float;
	final BOOLEAN_TYPE : Float;
	final FIRST_ORDERED_NODE_TYPE : Float;
	final NUMBER_TYPE : Float;
	final ORDERED_NODE_ITERATOR_TYPE : Float;
	final ORDERED_NODE_SNAPSHOT_TYPE : Float;
	final STRING_TYPE : Float;
	final UNORDERED_NODE_ITERATOR_TYPE : Float;
	final UNORDERED_NODE_SNAPSHOT_TYPE : Float;
	static var prototype : XPathResult;
	@:native("ANY_TYPE")
	static final ANY_TYPE_ : Float;
	@:native("ANY_UNORDERED_NODE_TYPE")
	static final ANY_UNORDERED_NODE_TYPE_ : Float;
	@:native("BOOLEAN_TYPE")
	static final BOOLEAN_TYPE_ : Float;
	@:native("FIRST_ORDERED_NODE_TYPE")
	static final FIRST_ORDERED_NODE_TYPE_ : Float;
	@:native("NUMBER_TYPE")
	static final NUMBER_TYPE_ : Float;
	@:native("ORDERED_NODE_ITERATOR_TYPE")
	static final ORDERED_NODE_ITERATOR_TYPE_ : Float;
	@:native("ORDERED_NODE_SNAPSHOT_TYPE")
	static final ORDERED_NODE_SNAPSHOT_TYPE_ : Float;
	@:native("STRING_TYPE")
	static final STRING_TYPE_ : Float;
	@:native("UNORDERED_NODE_ITERATOR_TYPE")
	static final UNORDERED_NODE_ITERATOR_TYPE_ : Float;
	@:native("UNORDERED_NODE_SNAPSHOT_TYPE")
	static final UNORDERED_NODE_SNAPSHOT_TYPE_ : Float;
}