package ts;

/**
	Wraps an anonymous structure typedef so that @:native field metadata works correctly.
	Generated by dts2hx. See https://github.com/HaxeFoundation/haxe/issues/5105
**/
@:genericBuild(ts.abstractanon.Macro.build())
class AbstractAnon<T> {}
