package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf4<T0, T1, T2, T3>(Dynamic) from T0 from T1 from T2 from T3 to T0 to T1 to T2 to T3 {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
	var asType2(get, never) : T2;
	private inline function get_asType2():T2 return this;
	var asType3(get, never) : T3;
	private inline function get_asType3():T3 return this;
}