package global;

typedef JQueryMouseEventObject = {
	var button : Float;
	var clientX : Float;
	var clientY : Float;
	var offsetX : Float;
	var offsetY : Float;
	/**
		The mouse position relative to the left edge of the document.
	**/
	var pageX : Float;
	/**
		The mouse position relative to the top edge of the document.
	**/
	var pageY : Float;
	var screenX : Float;
	var screenY : Float;
	var altKey : Bool;
	var ctrlKey : Bool;
	/**
		Indicates whether the META key was pressed when the event fired.
	**/
	var metaKey : Bool;
	var shiftKey : Bool;
	/**
		The current DOM element within the event bubbling phase.
	**/
	var currentTarget : js.html.DOMElement;
	/**
		An optional object of data passed to an event method when the current executing handler is bound.
	**/
	var data : Dynamic;
	/**
		The element where the currently-called jQuery event handler was attached.
	**/
	var delegateTarget : js.html.DOMElement;
	/**
		Returns whether event.preventDefault() was ever called on this event object.
	**/
	function isDefaultPrevented():Bool;
	/**
		Returns whether event.stopImmediatePropagation() was ever called on this event object.
	**/
	function isImmediatePropagationStopped():Bool;
	/**
		Returns whether event.stopPropagation() was ever called on this event object.
	**/
	function isPropagationStopped():Bool;
	/**
		The namespace specified when the event was triggered.
	**/
	var namespace : String;
	/**
		The browser's original Event object.
	**/
	var originalEvent : js.html.Event;
	/**
		If this method is called, the default action of the event will not be triggered.
	**/
	function preventDefault():Dynamic;
	/**
		The other DOM element involved in the event, if any.
	**/
	var relatedTarget : js.html.DOMElement;
	/**
		The last value returned by an event handler that was triggered by this event, unless the value was undefined.
	**/
	var result : Dynamic;
	/**
		Keeps the rest of the handlers from being executed and prevents the event from bubbling up the DOM tree.
	**/
	function stopImmediatePropagation():Void;
	/**
		Prevents the event from bubbling up the DOM tree, preventing any parent handlers from being notified of the event.
	**/
	function stopPropagation():Void;
	/**
		The DOM element that initiated the event.
	**/
	var target : js.html.DOMElement;
	/**
		For key or mouse events, this property indicates the specific key or button that was pressed.
	**/
	var which : Float;
	/**
		The **`bubbles`** read-only property of the Event interface indicates whether the event bubbles up through the DOM tree or not.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/bubbles)
	**/
	final bubbles : Bool;
	/**
		The **`cancelBubble`** property of the Event interface is deprecated.
	**/
	var cancelBubble : Bool;
	/**
		The **`cancelable`** read-only property of the Event interface indicates whether the event can be canceled, and therefore prevented as if the event never happened.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/cancelable)
	**/
	final cancelable : Bool;
	/**
		The read-only **`composed`** property of the or not the event will propagate across the shadow DOM boundary into the standard DOM.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composed)
	**/
	final composed : Bool;
	/**
		The **`defaultPrevented`** read-only property of the Event interface returns a boolean value indicating whether or not the call to Event.preventDefault() canceled the event.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/defaultPrevented)
	**/
	final defaultPrevented : Bool;
	/**
		The **`eventPhase`** read-only property of the being evaluated.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/eventPhase)
	**/
	final eventPhase : Float;
	/**
		The **`isTrusted`** read-only property of the when the event was generated by the user agent (including via user actions and programmatic methods such as HTMLElement.focus()), and `false` when the event was dispatched via The only exception is the `click` event, which initializes the `isTrusted` property to `false` in user agents.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/isTrusted)
	**/
	final isTrusted : Bool;
	/**
		The Event property **`returnValue`** indicates whether the default action for this event has been prevented or not.
	**/
	var returnValue : Bool;
	/**
		The deprecated **`Event.srcElement`** is an alias for the Event.target property.
	**/
	final srcElement : Null<js.html.EventTarget>;
	/**
		The **`timeStamp`** read-only property of the Event interface returns the time (in milliseconds) at which the event was created.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/timeStamp)
	**/
	final timeStamp : Float;
	/**
		The **`type`** read-only property of the Event interface returns a string containing the event's type.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/type)
	**/
	final type : String;
	/**
		The **`composedPath()`** method of the Event interface returns the event's path which is an array of the objects on which listeners will be invoked.
		
		[MDN Reference](https://developer.mozilla.org/docs/Web/API/Event/composedPath)
	**/
	function composedPath():Array<js.html.EventTarget>;
	/**
		The **`Event.initEvent()`** method is used to initialize the value of an event created using Document.createEvent().
	**/
	function initEvent(type:String, ?bubbles:Bool, ?cancelable:Bool):Void;
	final NONE : Int;
	final CAPTURING_PHASE : Int;
	final AT_TARGET : Int;
	final BUBBLING_PHASE : Int;
};