package typescript.ts;


/**
Generated from: test-definitions/typescript/typescript-extended.d.ts:5542:5
**/

typedef CompletionEntry = {
	var name: String;
	var kind: typescript.ts.ScriptElementKind;
	@:optional
	var kindModifiers: String;
	var sortText: String;
	@:optional
	var insertText: String;
	/**
	An optional span that indicates the text to be replaced by this completion item.
	If present, this span should be used instead of the default one.
	It will be set if the required span differs from the one generated by the default replacement behavior.
	**/
	@:optional
	var replacementSpan: typescript.ts.TextSpan;
	@:optional
	var hasAction: Bool;
	@:optional
	var source: String;
	@:optional
	var isRecommended: Bool;
}

