package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf32<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31>(Dynamic) from T0 from T1 from T2 from T3 from T4 from T5 from T6 from T7 from T8 from T9 from T10 from T11 from T12 from T13 from T14 from T15 from T16 from T17 from T18 from T19 from T20 from T21 from T22 from T23 from T24 from T25 from T26 from T27 from T28 from T29 from T30 from T31 to T0 to T1 to T2 to T3 to T4 to T5 to T6 to T7 to T8 to T9 to T10 to T11 to T12 to T13 to T14 to T15 to T16 to T17 to T18 to T19 to T20 to T21 to T22 to T23 to T24 to T25 to T26 to T27 to T28 to T29 to T30 to T31 { }