package ts;

/**
	AnyOf implementation generated by dts2hx
**/
extern abstract AnyOf13<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(Dynamic) from T0 from T1 from T2 from T3 from T4 from T5 from T6 from T7 from T8 from T9 from T10 from T11 from T12 to T0 to T1 to T2 to T3 to T4 to T5 to T6 to T7 to T8 to T9 to T10 to T11 to T12 { }