package ts;

/**
	AnyOf implementation generated by dts2hx
**/
extern abstract AnyOf6<T0, T1, T2, T3, T4, T5>(Dynamic) from T0 from T1 from T2 from T3 from T4 from T5 to T0 to T1 to T2 to T3 to T4 to T5 { }