package ts;

/**
	AnyOf implementation generated by dts2hx
**/
@:transitive extern abstract AnyOf8<T0, T1, T2, T3, T4, T5, T6, T7>(Dynamic) from T0 from T1 from T2 from T3 from T4 from T5 from T6 from T7 to T0 to T1 to T2 to T3 to T4 to T5 to T6 to T7 {
	var asType0(get, never) : T0;
	private inline function get_asType0():T0 return this;
	var asType1(get, never) : T1;
	private inline function get_asType1():T1 return this;
	var asType2(get, never) : T2;
	private inline function get_asType2():T2 return this;
	var asType3(get, never) : T3;
	private inline function get_asType3():T3 return this;
	var asType4(get, never) : T4;
	private inline function get_asType4():T4 return this;
	var asType5(get, never) : T5;
	private inline function get_asType5():T5 return this;
	var asType6(get, never) : T6;
	private inline function get_asType6():T6 return this;
	var asType7(get, never) : T7;
	private inline function get_asType7():T7 return this;
}