package node.util;

@:jsRequire("util", "types") @valueModuleOnly extern class Types {
	static function isAnyArrayBuffer(object:Dynamic):Bool;
	static function isArgumentsObject(object:Dynamic):Bool;
	static function isArrayBuffer(object:Dynamic):Bool;
	static function isAsyncFunction(object:Dynamic):Bool;
	static function isBooleanObject(object:Dynamic):Bool;
	static function isBoxedPrimitive(object:Dynamic):Bool;
	static function isDataView(object:Dynamic):Bool;
	static function isDate(object:Dynamic):Bool;
	static function isExternal(object:Dynamic):Bool;
	static function isFloat32Array(object:Dynamic):Bool;
	static function isFloat64Array(object:Dynamic):Bool;
	static function isGeneratorFunction(object:Dynamic):Bool;
	static function isGeneratorObject(object:Dynamic):Bool;
	static function isInt8Array(object:Dynamic):Bool;
	static function isInt16Array(object:Dynamic):Bool;
	static function isInt32Array(object:Dynamic):Bool;
	static function isMap(object:Dynamic):Bool;
	static function isMapIterator(object:Dynamic):Bool;
	static function isNativeError(object:Dynamic):Bool;
	static function isNumberObject(object:Dynamic):Bool;
	static function isPromise(object:Dynamic):Bool;
	static function isProxy(object:Dynamic):Bool;
	static function isRegExp(object:Dynamic):Bool;
	static function isSet(object:Dynamic):Bool;
	static function isSetIterator(object:Dynamic):Bool;
	static function isSharedArrayBuffer(object:Dynamic):Bool;
	static function isStringObject(object:Dynamic):Bool;
	static function isSymbolObject(object:Dynamic):Bool;
	static function isTypedArray(object:Dynamic):Bool;
	static function isUint8Array(object:Dynamic):Bool;
	static function isUint8ClampedArray(object:Dynamic):Bool;
	static function isUint16Array(object:Dynamic):Bool;
	static function isUint32Array(object:Dynamic):Bool;
	static function isWeakMap(object:Dynamic):Bool;
	static function isWeakSet(object:Dynamic):Bool;
	static function isWebAssemblyCompiledModule(object:Dynamic):Bool;
}