package js.lib;
/**
	Automatically generated tuple type implementation
	Generated by dts2hx v0.0.3
**/
@:forward @:forwardStatics extern abstract Tuple1<Base, T0>(Array<Base>) from Array<Base> to Array<Base> {
	public var element0(get, set) : T0;
	inline function get_element0():T0 return cast this[0];
	inline function set_element0(v:T0):T0 return cast this[0] = cast v;
}