package ts.html;
typedef ISVGPathSegClosePath = {
	final pathSegType : Float;
	final pathSegTypeAsLetter : String;
	final PATHSEG_ARC_ABS : Float;
	final PATHSEG_ARC_REL : Float;
	final PATHSEG_CLOSEPATH : Float;
	final PATHSEG_CURVETO_CUBIC_ABS : Float;
	final PATHSEG_CURVETO_CUBIC_REL : Float;
	final PATHSEG_CURVETO_CUBIC_SMOOTH_ABS : Float;
	final PATHSEG_CURVETO_CUBIC_SMOOTH_REL : Float;
	final PATHSEG_CURVETO_QUADRATIC_ABS : Float;
	final PATHSEG_CURVETO_QUADRATIC_REL : Float;
	final PATHSEG_CURVETO_QUADRATIC_SMOOTH_ABS : Float;
	final PATHSEG_CURVETO_QUADRATIC_SMOOTH_REL : Float;
	final PATHSEG_LINETO_ABS : Float;
	final PATHSEG_LINETO_HORIZONTAL_ABS : Float;
	final PATHSEG_LINETO_HORIZONTAL_REL : Float;
	final PATHSEG_LINETO_REL : Float;
	final PATHSEG_LINETO_VERTICAL_ABS : Float;
	final PATHSEG_LINETO_VERTICAL_REL : Float;
	final PATHSEG_MOVETO_ABS : Float;
	final PATHSEG_MOVETO_REL : Float;
	final PATHSEG_UNKNOWN : Float;
};