package ts.html;
/**
	The results generated by evaluating an XPath expression within the context of a given node.
**/
typedef IXPathResult = {
	final booleanValue : Bool;
	final invalidIteratorState : Bool;
	final numberValue : Float;
	final resultType : Float;
	final singleNodeValue : Null<INode>;
	final snapshotLength : Float;
	final stringValue : String;
	function iterateNext():Null<INode>;
	function snapshotItem(index:Float):Null<INode>;
	final ANY_TYPE : Float;
	final ANY_UNORDERED_NODE_TYPE : Float;
	final BOOLEAN_TYPE : Float;
	final FIRST_ORDERED_NODE_TYPE : Float;
	final NUMBER_TYPE : Float;
	final ORDERED_NODE_ITERATOR_TYPE : Float;
	final ORDERED_NODE_SNAPSHOT_TYPE : Float;
	final STRING_TYPE : Float;
	final UNORDERED_NODE_ITERATOR_TYPE : Float;
	final UNORDERED_NODE_SNAPSHOT_TYPE : Float;
};