package ts.html;
typedef WEBGL_draw_buffers = {
	@:overload(function(buffers:ts.lib.Iterable<Float>):Void { })
	function drawBuffersWEBGL(buffers:Array<Float>):Void;
	final COLOR_ATTACHMENT0_WEBGL : Float;
	final COLOR_ATTACHMENT10_WEBGL : Float;
	final COLOR_ATTACHMENT11_WEBGL : Float;
	final COLOR_ATTACHMENT12_WEBGL : Float;
	final COLOR_ATTACHMENT13_WEBGL : Float;
	final COLOR_ATTACHMENT14_WEBGL : Float;
	final COLOR_ATTACHMENT15_WEBGL : Float;
	final COLOR_ATTACHMENT1_WEBGL : Float;
	final COLOR_ATTACHMENT2_WEBGL : Float;
	final COLOR_ATTACHMENT3_WEBGL : Float;
	final COLOR_ATTACHMENT4_WEBGL : Float;
	final COLOR_ATTACHMENT5_WEBGL : Float;
	final COLOR_ATTACHMENT6_WEBGL : Float;
	final COLOR_ATTACHMENT7_WEBGL : Float;
	final COLOR_ATTACHMENT8_WEBGL : Float;
	final COLOR_ATTACHMENT9_WEBGL : Float;
	final DRAW_BUFFER0_WEBGL : Float;
	final DRAW_BUFFER10_WEBGL : Float;
	final DRAW_BUFFER11_WEBGL : Float;
	final DRAW_BUFFER12_WEBGL : Float;
	final DRAW_BUFFER13_WEBGL : Float;
	final DRAW_BUFFER14_WEBGL : Float;
	final DRAW_BUFFER15_WEBGL : Float;
	final DRAW_BUFFER1_WEBGL : Float;
	final DRAW_BUFFER2_WEBGL : Float;
	final DRAW_BUFFER3_WEBGL : Float;
	final DRAW_BUFFER4_WEBGL : Float;
	final DRAW_BUFFER5_WEBGL : Float;
	final DRAW_BUFFER6_WEBGL : Float;
	final DRAW_BUFFER7_WEBGL : Float;
	final DRAW_BUFFER8_WEBGL : Float;
	final DRAW_BUFFER9_WEBGL : Float;
	final MAX_COLOR_ATTACHMENTS_WEBGL : Float;
	final MAX_DRAW_BUFFERS_WEBGL : Float;
};