package js.lib;
/**
	Tuple type implementation generated by dts2hx
**/
@:forward @:forwardStatics extern abstract Tuple10<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(std.Array<Any>) from std.Array<Any> to std.Array<Any> {
	public inline function new(element0:T0, element1:T1, element2:T2, element3:T3, element4:T4, element5:T5, element6:T6, element7:T7, element8:T8, element9:T9) {
		set_element0(element0);
		set_element1(element1);
		set_element2(element2);
		set_element3(element3);
		set_element4(element4);
		set_element5(element5);
		set_element6(element6);
		set_element7(element7);
		set_element8(element8);
		set_element9(element9);
	}
	public var element0(get, set) : T0;
	inline function get_element0():T0 return cast this[0];
	inline function set_element0(v:T0):T0 return cast this[0] = cast v;
	public var element1(get, set) : T1;
	inline function get_element1():T1 return cast this[1];
	inline function set_element1(v:T1):T1 return cast this[1] = cast v;
	public var element2(get, set) : T2;
	inline function get_element2():T2 return cast this[2];
	inline function set_element2(v:T2):T2 return cast this[2] = cast v;
	public var element3(get, set) : T3;
	inline function get_element3():T3 return cast this[3];
	inline function set_element3(v:T3):T3 return cast this[3] = cast v;
	public var element4(get, set) : T4;
	inline function get_element4():T4 return cast this[4];
	inline function set_element4(v:T4):T4 return cast this[4] = cast v;
	public var element5(get, set) : T5;
	inline function get_element5():T5 return cast this[5];
	inline function set_element5(v:T5):T5 return cast this[5] = cast v;
	public var element6(get, set) : T6;
	inline function get_element6():T6 return cast this[6];
	inline function set_element6(v:T6):T6 return cast this[6] = cast v;
	public var element7(get, set) : T7;
	inline function get_element7():T7 return cast this[7];
	inline function set_element7(v:T7):T7 return cast this[7] = cast v;
	public var element8(get, set) : T8;
	inline function get_element8():T8 return cast this[8];
	inline function set_element8(v:T8):T8 return cast this[8] = cast v;
	public var element9(get, set) : T9;
	inline function get_element9():T9 return cast this[9];
	inline function set_element9(v:T9):T9 return cast this[9] = cast v;
}