package node.stream.stream;

@:jsRequire("stream", "Stream.promises") @valueModuleOnly extern class Promises {
	static function finished(stream:ts.AnyOf3<global.nodejs.ReadableStream, global.nodejs.WritableStream, global.nodejs.ReadWriteStream>, ?options:node.stream.stream.promises.FinishedOptions):js.lib.Promise<ts.Undefined>;
	@:overload(function<A:(PipelineSource<Dynamic>), T1:(PipelineTransform<A, Dynamic>), B:(ts.AnyOf5<global.nodejs.WritableStream, PipelineDestinationIterableFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>>, PipelineDestinationPromiseFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>, Dynamic>, PipelineDestinationIterableFunction<Dynamic>, PipelineDestinationPromiseFunction<Dynamic, Dynamic>>)>(source:A, transform1:T1, destination:B, ?options:PipelineOptions):PipelinePromise<B> { })
	@:overload(function<A:(PipelineSource<Dynamic>), T1:(PipelineTransform<A, Dynamic>), T2:(PipelineTransform<T1, Dynamic>), B:(ts.AnyOf5<global.nodejs.WritableStream, PipelineDestinationIterableFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>>, PipelineDestinationPromiseFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>, Dynamic>, PipelineDestinationIterableFunction<Dynamic>, PipelineDestinationPromiseFunction<Dynamic, Dynamic>>)>(source:A, transform1:T1, transform2:T2, destination:B, ?options:PipelineOptions):PipelinePromise<B> { })
	@:overload(function<A:(PipelineSource<Dynamic>), T1:(PipelineTransform<A, Dynamic>), T2:(PipelineTransform<T1, Dynamic>), T3:(PipelineTransform<T2, Dynamic>), B:(ts.AnyOf5<global.nodejs.WritableStream, PipelineDestinationIterableFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>>, PipelineDestinationPromiseFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>, Dynamic>, PipelineDestinationIterableFunction<Dynamic>, PipelineDestinationPromiseFunction<Dynamic, Dynamic>>)>(source:A, transform1:T1, transform2:T2, transform3:T3, destination:B, ?options:PipelineOptions):PipelinePromise<B> { })
	@:overload(function<A:(PipelineSource<Dynamic>), T1:(PipelineTransform<A, Dynamic>), T2:(PipelineTransform<T1, Dynamic>), T3:(PipelineTransform<T2, Dynamic>), T4:(PipelineTransform<T3, Dynamic>), B:(ts.AnyOf5<global.nodejs.WritableStream, PipelineDestinationIterableFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>>, PipelineDestinationPromiseFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>, Dynamic>, PipelineDestinationIterableFunction<Dynamic>, PipelineDestinationPromiseFunction<Dynamic, Dynamic>>)>(source:A, transform1:T1, transform2:T2, transform3:T3, transform4:T4, destination:B, ?options:PipelineOptions):PipelinePromise<B> { })
	@:overload(function(streams:haxe.ds.ReadOnlyArray<ts.AnyOf3<global.nodejs.ReadableStream, global.nodejs.WritableStream, global.nodejs.ReadWriteStream>>, ?options:PipelineOptions):js.lib.Promise<ts.Undefined> { })
	@:overload(function(stream1:global.nodejs.ReadableStream, stream2:ts.AnyOf2<global.nodejs.WritableStream, global.nodejs.ReadWriteStream>, streams:haxe.extern.Rest<ts.AnyOf3<global.nodejs.WritableStream, global.nodejs.ReadWriteStream, PipelineOptions>>):js.lib.Promise<ts.Undefined> { })
	static function pipeline<A:(PipelineSource<Dynamic>), B:(ts.AnyOf5<global.nodejs.WritableStream, PipelineDestinationIterableFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>>, PipelineDestinationPromiseFunction<ts.AnyOf2<String, node.buffer.Buffer<js.lib.ArrayBufferLike>>, Dynamic>, PipelineDestinationIterableFunction<Dynamic>, PipelineDestinationPromiseFunction<Dynamic, Dynamic>>)>(source:A, destination:B, ?options:PipelineOptions):PipelinePromise<B>;
}