package ts;

/**
	Tuple type implementation generated by dts2hx
**/
@:forward @:forwardStatics extern abstract Tuple1<T0>(std.Array<Any>) from std.Array<Any> to std.Array<Any> {
	public inline function new(element0:T0) {
		this = [element0];
	}
	public var element0(get, set) : T0;
	inline function get_element0():T0 return cast this[0];
	inline function set_element0(v:T0):T0 return cast this[0] = cast v;
}