package chart_js;

@:jsRequire("chart.js", "Chart") extern class Chart<TType:(String), TData, TLabel> {
	function new(item:ChartItem, config:ChartConfiguration<TType, TData, TLabel>);
	final platform : BasePlatform;
	final id : String;
	final canvas : js.html.CanvasElement;
	final ctx : js.html.CanvasRenderingContext2D;
	final config : ChartConfiguration<TType, TData, TLabel>;
	final width : Float;
	final height : Float;
	final aspectRatio : Float;
	final boxes : Array<LayoutItem>;
	final currentDevicePixelRatio : Float;
	final chartArea : ChartArea;
	final scales : haxe.DynamicAccess<Scale<CoreScaleOptions>>;
	final attached : Bool;
	var data : ChartData<TType, TData, TLabel>;
	var options : chart_js.types.utils.DeepPartial<CoreChartOptions<TType> & ElementChartOptions<TType> & PluginChartOptions<TType> & { } & ScaleChartOptions<TType>>;
	function clear():Chart<TType, TData, TLabel>;
	function stop():Chart<TType, TData, TLabel>;
	function resize(?width:Float, ?height:Float):Void;
	function ensureScalesHaveIDs():Void;
	function buildOrUpdateScales():Void;
	function buildOrUpdateControllers():Void;
	function reset():Void;
	function update(?mode:String):Void;
	function render():Void;
	function draw():Void;
	function getElementsAtEventForMode(e:js.html.Event, mode:String, options:InteractionOptions, useFinalPosition:Bool):Array<InteractionItem>;
	function getSortedVisibleDatasetMetas():Array<ChartMeta<Element<{ }, { }>, Element<{ }, { }>>>;
	function getDatasetMeta(datasetIndex:Float):ChartMeta<Element<{ }, { }>, Element<{ }, { }>>;
	function getVisibleDatasetCount():Float;
	function isDatasetVisible(datasetIndex:Float):Bool;
	function setDatasetVisibility(datasetIndex:Float, visible:Bool):Void;
	function toggleDataVisibility(index:Float):Void;
	function getDataVisibility(index:Float):Bool;
	function hide(datasetIndex:Float):Void;
	function show(datasetIndex:Float):Void;
	function getActiveElements():Array<ActiveElement>;
	function setActiveElements(active:Array<ActiveDataPoint>):Void;
	function destroy():Void;
	function toBase64Image(?type:String, ?quality:Any):String;
	function bindEvents():Void;
	function unbindEvents():Void;
	function updateHoverStyle(items:Element<{ }, { }>, mode:String, enabled:Bool):Void;
	function notifyPlugins(hook:String, ?args:haxe.DynamicAccess<Any>):Bool;
	static var prototype : Chart<Dynamic, Dynamic, Dynamic>;
	static final defaults : Defaults;
	static final overrides : {
		var line : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & LineControllerChartOptions;
		var bar : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & BarControllerChartOptions;
		var scatter : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & LineControllerChartOptions;
		var bubble : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String>;
		var pie : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & DoughnutControllerChartOptions;
		var doughnut : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & DoughnutControllerChartOptions;
		var polarArea : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & PolarAreaControllerChartOptions;
		var radar : CoreChartOptions<String> & ElementChartOptions<String> & PluginChartOptions<String> & DatasetChartOptions<String> & ScaleChartOptions<String> & LineControllerChartOptions;
	};
	static final version : String;
	static final instances : haxe.DynamicAccess<Chart<String, Array<Null<ts.AnyOf3<Float, ScatterDataPoint, BubbleDataPoint>>>, Any>>;
	static final registry : Registry;
	static function getChart(key:ts.AnyOf3<String, js.html.CanvasElement, js.html.CanvasRenderingContext2D>):Null<Chart<String, Array<Null<ts.AnyOf3<Float, ScatterDataPoint, BubbleDataPoint>>>, Any>>;
	static function register(items:haxe.extern.Rest<ChartComponentLike>):Void;
	static function unregister(items:haxe.extern.Rest<ChartComponentLike>):Void;
}