package js.lib;
/**
	Automatically generated tuple type implementation
	Generated by dts2hx v0.0.6
**/
@:forward @:forwardStatics extern abstract Tuple5<T0, T1, T2, T3, T4>(std.Array<Any>) from std.Array<Any> to std.Array<Any> {
	public var element0(get, set) : T0;
	inline function get_element0():T0 return cast this[0];
	inline function set_element0(v:T0):T0 return cast this[0] = cast v;
	public var element1(get, set) : T1;
	inline function get_element1():T1 return cast this[1];
	inline function set_element1(v:T1):T1 return cast this[1] = cast v;
	public var element2(get, set) : T2;
	inline function get_element2():T2 return cast this[2];
	inline function set_element2(v:T2):T2 return cast this[2] = cast v;
	public var element3(get, set) : T3;
	inline function get_element3():T3 return cast this[3];
	inline function set_element3(v:T3):T3 return cast this[3] = cast v;
	public var element4(get, set) : T4;
	inline function get_element4():T4 return cast this[4];
	inline function set_element4(v:T4):T4 return cast this[4] = cast v;
	public inline function new(element0:T0, element1:T1, element2:T2, element3:T3, element4:T4) {
		set_element0(element0);
		set_element1(element1);
		set_element2(element2);
		set_element3(element3);
		set_element4(element4);
	}
}