package global;

@:native("THREE") @valueModuleOnly extern class THREE {
	static function warn(?message:Dynamic, optionalParams:haxe.extern.Rest<Dynamic>):Void;
	static function error(?message:Dynamic, optionalParams:haxe.extern.Rest<Dynamic>):Void;
	static function log(?message:Dynamic, optionalParams:haxe.extern.Rest<Dynamic>):Void;
	static var ShaderLib : {
		var basic : global.three.Shader;
		var lambert : global.three.Shader;
		var phong : global.three.Shader;
		var standard : global.three.Shader;
		var matcap : global.three.Shader;
		var points : global.three.Shader;
		var dashed : global.three.Shader;
		var depth : global.three.Shader;
		var normal : global.three.Shader;
		var sprite : global.three.Shader;
		var background : global.three.Shader;
		var cube : global.three.Shader;
		var equirect : global.three.Shader;
		var distanceRGBA : global.three.Shader;
		var shadow : global.three.Shader;
		var physical : global.three.Shader;
	};
	static var UniformsLib : {
		var common : {
			var diffuse : global.three.IUniform;
			var opacity : global.three.IUniform;
			var map : global.three.IUniform;
			var uvTransform : global.three.IUniform;
			var alphaMap : global.three.IUniform;
		};
		var specularmap : {
			var specularMap : global.three.IUniform;
		};
		var envmap : {
			var envMap : global.three.IUniform;
			var flipEnvMap : global.three.IUniform;
			var reflectivity : global.three.IUniform;
			var refractionRatio : global.three.IUniform;
			var maxMipLevel : global.three.IUniform;
		};
		var aomap : {
			var aoMap : global.three.IUniform;
			var aoMapIntensity : global.three.IUniform;
		};
		var lightmap : {
			var lightMap : global.three.IUniform;
			var lightMapIntensity : global.three.IUniform;
		};
		var emissivemap : {
			var emissiveMap : global.three.IUniform;
		};
		var bumpmap : {
			var bumpMap : global.three.IUniform;
			var bumpScale : global.three.IUniform;
		};
		var normalmap : {
			var normalMap : global.three.IUniform;
			var normalScale : global.three.IUniform;
		};
		var displacementmap : {
			var displacementMap : global.three.IUniform;
			var displacementScale : global.three.IUniform;
			var displacementBias : global.three.IUniform;
		};
		var roughnessmap : {
			var roughnessMap : global.three.IUniform;
		};
		var metalnessmap : {
			var metalnessMap : global.three.IUniform;
		};
		var gradientmap : {
			var gradientMap : global.three.IUniform;
		};
		var fog : {
			var fogDensity : global.three.IUniform;
			var fogNear : global.three.IUniform;
			var fogFar : global.three.IUniform;
			var fogColor : global.three.IUniform;
		};
		var lights : {
			var ambientLightColor : global.three.IUniform;
			var directionalLights : {
				var value : Array<Dynamic>;
				var properties : {
					var direction : { };
					var color : { };
					var shadow : { };
					var shadowBias : { };
					var shadowRadius : { };
					var shadowMapSize : { };
				};
			};
			var directionalShadowMap : global.three.IUniform;
			var directionalShadowMatrix : global.three.IUniform;
			var spotLights : {
				var value : Array<Dynamic>;
				var properties : {
					var color : { };
					var position : { };
					var direction : { };
					var distance : { };
					var coneCos : { };
					var penumbraCos : { };
					var decay : { };
					var shadow : { };
					var shadowBias : { };
					var shadowRadius : { };
					var shadowMapSize : { };
				};
			};
			var spotShadowMap : global.three.IUniform;
			var spotShadowMatrix : global.three.IUniform;
			var pointLights : {
				var value : Array<Dynamic>;
				var properties : {
					var color : { };
					var position : { };
					var decay : { };
					var distance : { };
					var shadow : { };
					var shadowBias : { };
					var shadowRadius : { };
					var shadowMapSize : { };
				};
			};
			var pointShadowMap : global.three.IUniform;
			var pointShadowMatrix : global.three.IUniform;
			var hemisphereLights : {
				var value : Array<Dynamic>;
				var properties : {
					var direction : { };
					var skycolor : { };
					var groundColor : { };
				};
			};
			var rectAreaLights : {
				var value : Array<Dynamic>;
				var properties : {
					var color : { };
					var position : { };
					var width : { };
					var height : { };
				};
			};
		};
		var points : {
			var diffuse : global.three.IUniform;
			var opacity : global.three.IUniform;
			var size : global.three.IUniform;
			var scale : global.three.IUniform;
			var map : global.three.IUniform;
			var uvTransform : global.three.IUniform;
		};
	};
	static var ShaderChunk : {
		var alphamap_fragment : String;
		var alphamap_pars_fragment : String;
		var alphatest_fragment : String;
		var aomap_fragment : String;
		var aomap_pars_fragment : String;
		var begin_vertex : String;
		var beginnormal_vertex : String;
		var bsdfs : String;
		var bumpmap_pars_fragment : String;
		var clipping_planes_fragment : String;
		var clipping_planes_pars_fragment : String;
		var clipping_planes_pars_vertex : String;
		var clipping_planes_vertex : String;
		var color_fragment : String;
		var color_pars_fragment : String;
		var color_pars_vertex : String;
		var color_vertex : String;
		var common : String;
		var cube_frag : String;
		var cube_vert : String;
		var cube_uv_reflection_fragment : String;
		var defaultnormal_vertex : String;
		var depth_frag : String;
		var depth_vert : String;
		var distanceRGBA_frag : String;
		var distanceRGBA_vert : String;
		var displacementmap_vertex : String;
		var displacementmap_pars_vertex : String;
		var emissivemap_fragment : String;
		var emissivemap_pars_fragment : String;
		var encodings_pars_fragment : String;
		var encodings_fragment : String;
		var envmap_fragment : String;
		var envmap_pars_fragment : String;
		var envmap_pars_vertex : String;
		var envmap_vertex : String;
		var equirect_frag : String;
		var equirect_vert : String;
		var fog_fragment : String;
		var fog_pars_fragment : String;
		var linedashed_frag : String;
		var linedashed_vert : String;
		var lightmap_fragment : String;
		var lightmap_pars_fragment : String;
		var lights_lambert_vertex : String;
		var lights_pars_begin : String;
		var lights_pars_map : String;
		var lights_phong_fragment : String;
		var lights_phong_pars_fragment : String;
		var lights_physical_fragment : String;
		var lights_physical_pars_fragment : String;
		var lights_fragment_begin : String;
		var lights_fragment_maps : String;
		var lights_fragment_end : String;
		var logdepthbuf_fragment : String;
		var logdepthbuf_pars_fragment : String;
		var logdepthbuf_pars_vertex : String;
		var logdepthbuf_vertex : String;
		var map_fragment : String;
		var map_pars_fragment : String;
		var map_particle_fragment : String;
		var map_particle_pars_fragment : String;
		var meshbasic_frag : String;
		var meshbasic_vert : String;
		var meshlambert_frag : String;
		var meshlambert_vert : String;
		var meshphong_frag : String;
		var meshphong_vert : String;
		var meshphysical_frag : String;
		var meshphysical_vert : String;
		var metalnessmap_fragment : String;
		var metalnessmap_pars_fragment : String;
		var morphnormal_vertex : String;
		var morphtarget_pars_vertex : String;
		var morphtarget_vertex : String;
		var normal_flip : String;
		var normal_frag : String;
		var normal_fragment_begin : String;
		var normal_fragment_maps : String;
		var normal_vert : String;
		var normalmap_pars_fragment : String;
		var packing : String;
		var points_frag : String;
		var points_vert : String;
		var shadow_frag : String;
		var shadow_vert : String;
		var premultiplied_alpha_fragment : String;
		var project_vertex : String;
		var roughnessmap_fragment : String;
		var roughnessmap_pars_fragment : String;
		var shadowmap_pars_fragment : String;
		var shadowmap_pars_vertex : String;
		var shadowmap_vertex : String;
		var shadowmask_pars_fragment : String;
		var skinbase_vertex : String;
		var skinning_pars_vertex : String;
		var skinning_vertex : String;
		var skinnormal_vertex : String;
		var specularmap_fragment : String;
		var specularmap_pars_fragment : String;
		var tonemapping_fragment : String;
		var tonemapping_pars_fragment : String;
		var uv2_pars_fragment : String;
		var uv2_pars_vertex : String;
		var uv2_vertex : String;
		var uv_pars_fragment : String;
		var uv_pars_vertex : String;
		var uv_vertex : String;
		var worldpos_vertex : String;
	};
	static var LineStrip : Float;
	static var LinePieces : Float;
	static var TextureIdCount : Float;
	static var MaterialIdCount : Float;
	static var DefaultLoadingManager : global.three.LoadingManager;
	static var AudioContext : js.html.audio.AudioContext;
	static var GeometryIdCount : Float;
	static var Object3DIdCount : Float;
	static var REVISION : String;
	static var CullFaceNone : global.three.CullFace;
	static var CullFaceBack : global.three.CullFace;
	static var CullFaceFront : global.three.CullFace;
	static var CullFaceFrontBack : global.three.CullFace;
	static var FrontFaceDirectionCW : global.three.FrontFaceDirection;
	static var FrontFaceDirectionCCW : global.three.FrontFaceDirection;
	static var BasicShadowMap : global.three.ShadowMapType;
	static var PCFShadowMap : global.three.ShadowMapType;
	static var PCFSoftShadowMap : global.three.ShadowMapType;
	static var FrontSide : global.three.Side;
	static var BackSide : global.three.Side;
	static var DoubleSide : global.three.Side;
	static var FlatShading : global.three.Shading;
	static var SmoothShading : global.three.Shading;
	static var NoColors : global.three.Colors;
	static var FaceColors : global.three.Colors;
	static var VertexColors : global.three.Colors;
	static var NoBlending : global.three.Blending;
	static var NormalBlending : global.three.Blending;
	static var AdditiveBlending : global.three.Blending;
	static var SubtractiveBlending : global.three.Blending;
	static var MultiplyBlending : global.three.Blending;
	static var CustomBlending : global.three.Blending;
	static var AddEquation : global.three.BlendingEquation;
	static var SubtractEquation : global.three.BlendingEquation;
	static var ReverseSubtractEquation : global.three.BlendingEquation;
	static var MinEquation : global.three.BlendingEquation;
	static var MaxEquation : global.three.BlendingEquation;
	static var ZeroFactor : global.three.BlendingDstFactor;
	static var OneFactor : global.three.BlendingDstFactor;
	static var SrcColorFactor : global.three.BlendingDstFactor;
	static var OneMinusSrcColorFactor : global.three.BlendingDstFactor;
	static var SrcAlphaFactor : global.three.BlendingDstFactor;
	static var OneMinusSrcAlphaFactor : global.three.BlendingDstFactor;
	static var DstAlphaFactor : global.three.BlendingDstFactor;
	static var OneMinusDstAlphaFactor : global.three.BlendingDstFactor;
	static var DstColorFactor : global.three.BlendingDstFactor;
	static var OneMinusDstColorFactor : global.three.BlendingDstFactor;
	static var SrcAlphaSaturateFactor : global.three.BlendingSrcFactor;
	static var NeverDepth : global.three.DepthModes;
	static var AlwaysDepth : global.three.DepthModes;
	static var LessDepth : global.three.DepthModes;
	static var LessEqualDepth : global.three.DepthModes;
	static var EqualDepth : global.three.DepthModes;
	static var GreaterEqualDepth : global.three.DepthModes;
	static var GreaterDepth : global.three.DepthModes;
	static var NotEqualDepth : global.three.DepthModes;
	static var MultiplyOperation : global.three.Combine;
	static var MixOperation : global.three.Combine;
	static var AddOperation : global.three.Combine;
	static var NoToneMapping : global.three.ToneMapping;
	static var LinearToneMapping : global.three.ToneMapping;
	static var ReinhardToneMapping : global.three.ToneMapping;
	static var Uncharted2ToneMapping : global.three.ToneMapping;
	static var CineonToneMapping : global.three.ToneMapping;
	static var UVMapping : global.three.Mapping;
	static var CubeReflectionMapping : global.three.Mapping;
	static var CubeRefractionMapping : global.three.Mapping;
	static var EquirectangularReflectionMapping : global.three.Mapping;
	static var EquirectangularRefractionMapping : global.three.Mapping;
	static var SphericalReflectionMapping : global.three.Mapping;
	static var CubeUVReflectionMapping : global.three.Mapping;
	static var CubeUVRefractionMapping : global.three.Mapping;
	static var RepeatWrapping : global.three.Wrapping;
	static var ClampToEdgeWrapping : global.three.Wrapping;
	static var MirroredRepeatWrapping : global.three.Wrapping;
	static var NearestFilter : global.three.TextureFilter;
	static var NearestMipmapNearestFilter : global.three.TextureFilter;
	static var NearestMipMapNearestFilter : global.three.TextureFilter;
	static var NearestMipmapLinearFilter : global.three.TextureFilter;
	static var NearestMipMapLinearFilter : global.three.TextureFilter;
	static var LinearFilter : global.three.TextureFilter;
	static var LinearMipmapNearestFilter : global.three.TextureFilter;
	static var LinearMipMapNearestFilter : global.three.TextureFilter;
	static var LinearMipmapLinearFilter : global.three.TextureFilter;
	static var LinearMipMapLinearFilter : global.three.TextureFilter;
	static var UnsignedByteType : global.three.TextureDataType;
	static var ByteType : global.three.TextureDataType;
	static var ShortType : global.three.TextureDataType;
	static var UnsignedShortType : global.three.TextureDataType;
	static var IntType : global.three.TextureDataType;
	static var UnsignedIntType : global.three.TextureDataType;
	static var FloatType : global.three.TextureDataType;
	static var HalfFloatType : global.three.TextureDataType;
	static var UnsignedShort4444Type : global.three.PixelType;
	static var UnsignedShort5551Type : global.three.PixelType;
	static var UnsignedShort565Type : global.three.PixelType;
	static var UnsignedInt248Type : global.three.PixelType;
	static var AlphaFormat : global.three.PixelFormat;
	static var RGBFormat : global.three.PixelFormat;
	static var RGBAFormat : global.three.PixelFormat;
	static var LuminanceFormat : global.three.PixelFormat;
	static var LuminanceAlphaFormat : global.three.PixelFormat;
	static var RGBEFormat : global.three.PixelFormat;
	static var DepthFormat : global.three.PixelFormat;
	static var DepthStencilFormat : global.three.PixelFormat;
	static var RedFormat : global.three.PixelFormat;
	static var RGB_S3TC_DXT1_Format : global.three.CompressedPixelFormat;
	static var RGBA_S3TC_DXT1_Format : global.three.CompressedPixelFormat;
	static var RGBA_S3TC_DXT3_Format : global.three.CompressedPixelFormat;
	static var RGBA_S3TC_DXT5_Format : global.three.CompressedPixelFormat;
	static var RGB_PVRTC_4BPPV1_Format : global.three.CompressedPixelFormat;
	static var RGB_PVRTC_2BPPV1_Format : global.three.CompressedPixelFormat;
	static var RGBA_PVRTC_4BPPV1_Format : global.three.CompressedPixelFormat;
	static var RGBA_PVRTC_2BPPV1_Format : global.three.CompressedPixelFormat;
	static var RGB_ETC1_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_4x4_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_5x4_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_5x5_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_6x5_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_6x6_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_8x5_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_8x6_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_8x8_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_10x5_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_10x6_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_10x8_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_10x10_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_12x10_Format : global.three.CompressedPixelFormat;
	static var RGBA_ASTC_12x12_Format : global.three.CompressedPixelFormat;
	static var LoopOnce : global.three.AnimationActionLoopStyles;
	static var LoopRepeat : global.three.AnimationActionLoopStyles;
	static var LoopPingPong : global.three.AnimationActionLoopStyles;
	static var InterpolateDiscrete : global.three.InterpolationModes;
	static var InterpolateLinear : global.three.InterpolationModes;
	static var InterpolateSmooth : global.three.InterpolationModes;
	static var ZeroCurvatureEnding : global.three.InterpolationEndingModes;
	static var ZeroSlopeEnding : global.three.InterpolationEndingModes;
	static var WrapAroundEnding : global.three.InterpolationEndingModes;
	static var TrianglesDrawMode : global.three.TrianglesDrawModes;
	static var TriangleStripDrawMode : global.three.TrianglesDrawModes;
	static var TriangleFanDrawMode : global.three.TrianglesDrawModes;
	static var LinearEncoding : global.three.TextureEncoding;
	static var sRGBEncoding : global.three.TextureEncoding;
	static var GammaEncoding : global.three.TextureEncoding;
	static var RGBEEncoding : global.three.TextureEncoding;
	static var LogLuvEncoding : global.three.TextureEncoding;
	static var RGBM7Encoding : global.three.TextureEncoding;
	static var RGBM16Encoding : global.three.TextureEncoding;
	static var RGBDEncoding : global.three.TextureEncoding;
	static var BasicDepthPacking : global.three.DepthPackingStrategies;
	static var RGBADepthPacking : global.three.DepthPackingStrategies;
	static var TangentSpaceNormalMap : global.three.NormalMapTypes;
	static var ObjectSpaceNormalMap : global.three.NormalMapTypes;
	static var ZeroStencilOp : global.three.StencilOp;
	static var KeepStencilOp : global.three.StencilOp;
	static var ReplaceStencilOp : global.three.StencilOp;
	static var IncrementStencilOp : global.three.StencilOp;
	static var DecrementStencilOp : global.three.StencilOp;
	static var IncrementWrapStencilOp : global.three.StencilOp;
	static var DecrementWrapStencilOp : global.three.StencilOp;
	static var InvertStencilOp : global.three.StencilOp;
	static var NeverStencilFunc : global.three.StencilFunc;
	static var LessStencilFunc : global.three.StencilFunc;
	static var EqualStencilFunc : global.three.StencilFunc;
	static var LessEqualStencilFunc : global.three.StencilFunc;
	static var GreaterStencilFunc : global.three.StencilFunc;
	static var NotEqualStencilFunc : global.three.StencilFunc;
	static var GreaterEqualStencilFunc : global.three.StencilFunc;
	static var AlwaysStencilFunc : global.three.StencilFunc;
}