// Generated by Haxe 5.0.0-preview.1+06a76b8
import build_Testlib from "./build/testlib";
import { Animal as build_testlib_Animal } from "./build/testlib";
(function ($global) { "use strict";
class TestESMMinimal {
	static main() {
		let a = new build_testlib_Animal("cat",4);
		console.log("TestESMMinimal.hx:8:","Animal: " + a.name + ", legs: " + a.legs);
		console.log("TestESMMinimal.hx:9:","Direction up: " + build.testlib.Direction.Up);
		console.log("TestESMMinimal.hx:10:","greet: " + build_Testlib.greet("world"));
		console.log("TestESMMinimal.hx:11:","ESM runtime: PASSED");
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
TestESMMinimal.main();
})({});
