package undici_types;

@:jsRequire("undici-types/api") @valueModuleOnly extern class Api {
	/**
		Performs an HTTP request.
	**/
	static function request(url:ts.AnyOf3<String, node.url.URL, node.url.UrlObject>, ?options:{ @:optional var dispatcher : Dispatcher; } & { /** Default: `null` **/ @:optional var signal : Any; /** Default: `null` **/ @:optional var body : ts.AnyOf5<String, js.lib.Uint8Array_<js.lib.ArrayBufferLike>, node.stream.stream.Readable, global.Buffer<js.lib.ArrayBufferLike>, FormData>; /** Whether the request should stablish a keep-alive or not. Default `false` **/ @:optional var reset : Bool; /** Default: `null` **/ @:optional var opaque : Any; /** Default: `64 KiB` **/ @:optional var highWaterMark : Float; /** Upgrade the request. Should be used to specify the kind of upgrade i.e. `'Websocket'`. Default: `method === 'CONNECT' || null`. **/ @:optional var upgrade : ts.AnyOf2<String, Bool>; /** Default: `null` **/ @:optional var headers : ts.AnyOf3<Array<String>, haxe.DynamicAccess<Null<ts.AnyOf2<String, Array<String>>>>, Iterable<ts.Tuple2<String, Null<ts.AnyOf2<String, Array<String>>>>>>; /** The amount of time, in milliseconds, the parser will wait to receive the complete HTTP headers. Defaults to 300 seconds. **/ @:optional var headersTimeout : Float; /** Default: 0 **/ @:optional var maxRedirections : Float; /** Default: false **/ @:optional var redirectionLimitReached : Bool; /** Default: `null` **/ @:optional var responseHeader : String; /** Default: `null` **/ @:optional dynamic function onInfo(info:{ var statusCode : Float; var headers : haxe.DynamicAccess<ts.AnyOf2<String, Array<String>>>; }):Void; /** Query string params to be embedded in the request URL. Default: `null` **/ @:optional var query : haxe.DynamicAccess<Dynamic>; /** Whether the requests can be safely retried or not. If `false` the request won't be sent until all preceding requests in the pipeline have completed. Default: `true` if `method` is `HEAD` or `GET`. **/ @:optional var idempotent : Bool; /** Whether the response is expected to take a long time and would end up blocking the pipeline. When this is set to `true` further pipelining will be avoided on the same connection until headers have been received. **/ @:optional var blocking : Bool; /** The timeout after which a request will time out, in milliseconds. Monitors time between receiving body data. Use 0 to disable it entirely. Defaults to 300 seconds. **/ @:optional var bodyTimeout : Float; /** Whether Undici should throw an error upon receiving a 4xx or 5xx response from the server. Defaults to false **/ @:optional var throwOnError : Bool; /** For H2, it appends the expect: 100-continue header, and halts the request body until a 100-continue is received from the remote server **/ @:optional var expectContinue : Bool; } & { @:optional var method : undici_types.dispatcher.HttpMethod; }):js.lib.Promise<undici_types.dispatcher.ResponseData>;
	/**
		A faster version of `request`.
	**/
	static function stream(url:ts.AnyOf3<String, node.url.URL, node.url.UrlObject>, options:{ @:optional var dispatcher : Dispatcher; } & { /** Default: `null` **/ @:optional var signal : Any; /** Default: `null` **/ @:optional var body : ts.AnyOf5<String, js.lib.Uint8Array_<js.lib.ArrayBufferLike>, node.stream.stream.Readable, global.Buffer<js.lib.ArrayBufferLike>, FormData>; /** Whether the request should stablish a keep-alive or not. Default `false` **/ @:optional var reset : Bool; var method : undici_types.dispatcher.HttpMethod; /** Default: `null` **/ @:optional var opaque : Any; /** Default: `64 KiB` **/ @:optional var highWaterMark : Float; /** Upgrade the request. Should be used to specify the kind of upgrade i.e. `'Websocket'`. Default: `method === 'CONNECT' || null`. **/ @:optional var upgrade : ts.AnyOf2<String, Bool>; /** Default: `null` **/ @:optional var headers : ts.AnyOf3<Array<String>, haxe.DynamicAccess<Null<ts.AnyOf2<String, Array<String>>>>, Iterable<ts.Tuple2<String, Null<ts.AnyOf2<String, Array<String>>>>>>; /** The amount of time, in milliseconds, the parser will wait to receive the complete HTTP headers. Defaults to 300 seconds. **/ @:optional var headersTimeout : Float; /** Default: 0 **/ @:optional var maxRedirections : Float; /** Default: false **/ @:optional var redirectionLimitReached : Bool; /** Default: `null` **/ @:optional var responseHeader : String; /** Default: `null` **/ @:optional dynamic function onInfo(info:{ var statusCode : Float; var headers : haxe.DynamicAccess<ts.AnyOf2<String, Array<String>>>; }):Void; /** Query string params to be embedded in the request URL. Default: `null` **/ @:optional var query : haxe.DynamicAccess<Dynamic>; /** Whether the requests can be safely retried or not. If `false` the request won't be sent until all preceding requests in the pipeline have completed. Default: `true` if `method` is `HEAD` or `GET`. **/ @:optional var idempotent : Bool; /** Whether the response is expected to take a long time and would end up blocking the pipeline. When this is set to `true` further pipelining will be avoided on the same connection until headers have been received. **/ @:optional var blocking : Bool; /** The timeout after which a request will time out, in milliseconds. Monitors time between receiving body data. Use 0 to disable it entirely. Defaults to 300 seconds. **/ @:optional var bodyTimeout : Float; /** Whether Undici should throw an error upon receiving a 4xx or 5xx response from the server. Defaults to false **/ @:optional var throwOnError : Bool; /** For H2, it appends the expect: 100-continue header, and halts the request body until a 100-continue is received from the remote server **/ @:optional var expectContinue : Bool; }, factory:undici_types.dispatcher.StreamFactory):js.lib.Promise<undici_types.dispatcher.StreamData>;
	/**
		For easy use with `stream.pipeline`.
	**/
	static function pipeline(url:ts.AnyOf3<String, node.url.URL, node.url.UrlObject>, options:{ @:optional var dispatcher : Dispatcher; } & { /** Default: `null` **/ @:optional var signal : Any; /** Default: `null` **/ @:optional var body : ts.AnyOf5<String, js.lib.Uint8Array_<js.lib.ArrayBufferLike>, node.stream.stream.Readable, global.Buffer<js.lib.ArrayBufferLike>, FormData>; /** Whether the request should stablish a keep-alive or not. Default `false` **/ @:optional var reset : Bool; var method : undici_types.dispatcher.HttpMethod; /** Default: `null` **/ @:optional var opaque : Any; /** Default: `64 KiB` **/ @:optional var highWaterMark : Float; /** Upgrade the request. Should be used to specify the kind of upgrade i.e. `'Websocket'`. Default: `method === 'CONNECT' || null`. **/ @:optional var upgrade : ts.AnyOf2<String, Bool>; /** Default: `null` **/ @:optional var headers : ts.AnyOf3<Array<String>, haxe.DynamicAccess<Null<ts.AnyOf2<String, Array<String>>>>, Iterable<ts.Tuple2<String, Null<ts.AnyOf2<String, Array<String>>>>>>; /** The amount of time, in milliseconds, the parser will wait to receive the complete HTTP headers. Defaults to 300 seconds. **/ @:optional var headersTimeout : Float; /** `true` if the `handler` will return an object stream. Default: `false` **/ @:optional var objectMode : Bool; /** Default: 0 **/ @:optional var maxRedirections : Float; /** Default: false **/ @:optional var redirectionLimitReached : Bool; /** Default: `null` **/ @:optional var responseHeader : String; /** Default: `null` **/ @:optional dynamic function onInfo(info:{ var statusCode : Float; var headers : haxe.DynamicAccess<ts.AnyOf2<String, Array<String>>>; }):Void; /** Query string params to be embedded in the request URL. Default: `null` **/ @:optional var query : haxe.DynamicAccess<Dynamic>; /** Whether the requests can be safely retried or not. If `false` the request won't be sent until all preceding requests in the pipeline have completed. Default: `true` if `method` is `HEAD` or `GET`. **/ @:optional var idempotent : Bool; /** Whether the response is expected to take a long time and would end up blocking the pipeline. When this is set to `true` further pipelining will be avoided on the same connection until headers have been received. **/ @:optional var blocking : Bool; /** The timeout after which a request will time out, in milliseconds. Monitors time between receiving body data. Use 0 to disable it entirely. Defaults to 300 seconds. **/ @:optional var bodyTimeout : Float; /** Whether Undici should throw an error upon receiving a 4xx or 5xx response from the server. Defaults to false **/ @:optional var throwOnError : Bool; /** For H2, it appends the expect: 100-continue header, and halts the request body until a 100-continue is received from the remote server **/ @:optional var expectContinue : Bool; }, handler:undici_types.dispatcher.PipelineHandler):node.stream.stream.Duplex;
	/**
		Starts two-way communications with the requested resource.
	**/
	static function connect(url:ts.AnyOf3<String, node.url.URL, node.url.UrlObject>, ?options:{ @:optional var dispatcher : Dispatcher; } & { /** Default: `null` **/ @:optional var signal : Any; /** This argument parameter is passed through to `ConnectData` **/ @:optional var opaque : Any; /** Default: `null` **/ @:optional var headers : ts.AnyOf2<Array<String>, haxe.DynamicAccess<Null<ts.AnyOf2<String, Array<String>>>>>; /** Default: 0 **/ @:optional var maxRedirections : Float; /** Default: false **/ @:optional var redirectionLimitReached : Bool; /** Default: `null` **/ @:optional var responseHeader : String; }):js.lib.Promise<undici_types.dispatcher.ConnectData>;
	/**
		Upgrade to a different protocol.
	**/
	static function upgrade(url:ts.AnyOf3<String, node.url.URL, node.url.UrlObject>, ?options:{ @:optional var dispatcher : Dispatcher; } & { /** Default: `null` **/ @:optional var signal : Any; /** Default: `'GET'` **/ @:optional var method : String; /** Default: `null` **/ @:optional var headers : ts.AnyOf2<Array<String>, haxe.DynamicAccess<Null<ts.AnyOf2<String, Array<String>>>>>; /** A string of comma separated protocols, in descending preference order. Default: `'Websocket'` **/ @:optional var protocol : String; /** Default: 0 **/ @:optional var maxRedirections : Float; /** Default: false **/ @:optional var redirectionLimitReached : Bool; /** Default: `null` **/ @:optional var responseHeader : String; }):js.lib.Promise<undici_types.dispatcher.UpgradeData>;
}